CXA-8705
nutanixgso/salt pull request #11
Opened 2017-01-19 15:35 UTC by simula67

Accept only expected IP address for static IP provisioning

Problem
=======
During provisioning, sometimes the deployed VM gets a different IP
address ( possibly because the template was created fro a VM carrying
a specific IP address ). Salt picks up this IP address from guest tools
and then continues to proceed. This causes an infinite loop in
wait_for_winexesvc

Solution
========
For static IP provisioning only accept the expected IP address as valid

### What does this PR do?

### What issues does this PR fix or reference?

### Previous Behavior

### New Behavior

### Tests written?
- [ ] Yes
- [ ] No

2017-01-19 18:24 UTC, ghost requested changes

2017-01-19 18:24 UTC, sreejithkesavan commented on salt/cloud/clouds/vmware.py
> +            expected_ip = vm_['devices']['network']['Network adapter 1']['ip']
We should iterate thought the list of network adapters and validate for each ips.

2017-01-20 09:42 UTC, simula67 commented
@sreejithkesavan don't merge

2017-01-20 10:02 UTC, simula67 commented
@sreejithkesavan seems to go forward. Please merge

2017-01-20 10:14 UTC, ghost approved these changes

2017-01-20 10:14 UTC, merged